---
packages:
  official:
    - adobe-source-han-sans-otc-fonts
    - cups
    - flameshot
    - hplip
    - libreoffice-fresh
    - hunspell
    - hunspell-de
    - hunspell-en_us
    - hunspell-fr
    - python-pyqt
    - redshift
    - sane
    - simple-scan
    - ttf-noto-nerd   # Used as System UI font
    - xfce4-docklike-plugin
  aur:
    # - spotify
    - ulauncher
    # - whitesur-gtk-theme
    # - whitesur-cursor-theme-git
    # - whitesur-icon-theme
