# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/desktop.yml
    name: desktop
- name: Install desktop utilities
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: desktop utilities
    packages: "{{ desktop.packages }}"
