# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/backup.yml
    name: backup
- name: Install backup utilities
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: backup utilities
    packages: "{{ backup.packages }}"
