# vi: ft=yaml.ansible
---
- name: Install crun, jack2
  community.general.pacman:
    name:
      - crun
      - jack2
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/containers.yml
    name: containers
- name: Install containers tools
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: containers orchestration tools
    packages: "{{ containers.packages }}"
- name: "Adding existing unprivileged user to groups docker and libvirt"
  ansible.builtin.user:
    name: '{{ unprivileged_user }}'
    groups: docker,libvirt
    append: true
- name:
    Ensure slirp4netns is set in section "[network]"
    (https://wiki.archlinux.org/title/Podman#Networking)
  community.general.ini_file:
    path: /etc/containers/containers.conf
    section: network
    option: default_rootless_network_cmd
    value: '"slirp4netns"'
    state: present
    mode: '0644'
