# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/iac.yml
    name: iac
- name: Install IaC tools
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: iac tools
    packages: "{{ iac.packages }}"
