# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/latex.yml
    name: latex
- name: Install LaTex tools
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: LaTex tools
    packages: "{{ latex.packages }}"
