# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/neovim.yml
    name: neovim
- name: Install neovim tools
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: Neovim, LSPs and linters
    packages: "{{ neovim.packages }}"
