# vi: ft=yaml.ansible
---
- name: Install network dependencies
  community.general.pacman:
    name:
      # Required by proton-vpn-gtk-app
      - gnome-keyring
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/network.yml
    name: network
- name: Install network tools
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: network tools
    packages: "{{ network.packages }}"
