# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/php.yml
    name: php
- name: Install PHP toolchain
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: PHP toolchain
    packages: "{{ php.packages }}"
