# vi: ft=yaml.ansible
---
- name: Import variables
  ansible.builtin.include_vars:
    file: vars/security.yml
    name: security
- name: Install security tools
  ansible.builtin.import_tasks:
    file: tasks/install_packages.yaml
  vars:
    topic: security tools
    packages: "{{ security.packages }}"
